# Generated by Django 3.2.5 on 2021-07-27 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['name'], 'verbose_name_plural': 'communities'},
        ),
    ]
