# Generated by Django 3.2.5 on 2021-08-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_alter_applicant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificationdocument',
            name='document_no',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
